# Generated by Django 4.1.5 on 2023-01-24 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='details',
            field=models.CharField(default='HELLO, WORLD!', max_length=300),
        ),
    ]
